collections:
  friends:
      output: true
      permalink: /friends/:path/
  people:
      output: true
      permalink: /people/:path/
  venues:
      output: true
      permalink: /venues/:path/

events:
  past: []
  future: []


# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vespres al Col·legi

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Xerrades

description: > # this means to ignore newlines until "baseurl:"
  Xerrades del Col·legi d'Enginyers d'Informàtics.
  Coneixements generals d'informàtica,
  introducció a noves técnologies,
  i novetats de la comunitat.
  Lliure accés a tothom interessat.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vespres.coeinf.com" # the base hostname & protocol for your site

#These settings might be able to go?
author: David Rodenas
twitter_username: drpicox
github_username:  drpicox/evento
company_name: Col·legi d'Enginyeria Informatica

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

exclude:
  - old
  - node_modules
