collections:
  activities:
      output: true
      permalink: /activities/:path/
  contributors:
      output: true
      permalink: /contributors/:path/
  events:
      output: true
      permalink: /events/:path/
  friends:
      output: true
      permalink: /friends/:path/
  tracks:
      output: true
      permalink: /tracks/:path/
  venues:
      output: true
      permalink: /venues/:path/

defaults:
  - scope:
      path: ""
      type: activities
    values:
      layout: activity
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor
  - scope:
      path: ""
      type: events
    values:
      layout: event
  - scope:
      path: ""
      type: friends
    values:
      layout: friend
  - scope:
      path: ""
      type: tracks
    values:
      layout: track
  - scope:
      path: ""
      type: venues
    values:
      layout: venue

events:
  past: []
  future: []


# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: els Vespres del Col·legi

description: > # this means to ignore newlines until "baseurl:"
  Xerrades del Col·legi d'Enginyers d'Informàtics.
  Coneixements generals d'informàtica,
  introducció a noves técnologies,
  i novetats de la comunitat.
  Lliure accés a tothom interessat.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vespres.coeinf.com" # the base hostname & protocol for your site

#These settings might be able to go?
author: David Rodenas
twitter_username: coeinf
github_username:  coeinf/evento
company_name: Col·legi d'Enginyeria Informatica

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /events/:title

exclude:
  - old
  - node_modules

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
